// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/12/2026, 5:32:32 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/mac/Documents/wisekings/storefront/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/storefront/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/storefront/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/storefront/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/storefront/plugins/**/*.{js,ts,mjs}","/Users/mac/Documents/wisekings/storefront/composables/**/*.{js,ts,mjs}","/Users/mac/Documents/wisekings/storefront/utils/**/*.{js,ts,mjs}","/Users/mac/Documents/wisekings/storefront/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/storefront/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/storefront/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/storefront/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;